import { DateTime } from "luxon";
import { Promotion, zone } from "./promotion";
const details = [
  [
    "Kopi Social",
    "A little kopi. A lot to love.",
    "Cafés",
    "1-for-1",
    "Two iced lattes, one lovely afternoon.",
    "Tanjong Pagar",
    "7 Wallich Street",
    1.277,
    103.846,
  ],
  [
    "Rice & Company",
    "Your lunch break, upgraded.",
    "Meals",
    "$5 off",
    "A comforting rice bowl with a little extra left in your pocket.",
    "City Hall",
    "252 North Bridge Road",
    1.2932,
    103.852,
  ],
  [
    "Sunday Scoops",
    "Make room for a second scoop.",
    "Desserts",
    "2 for $8",
    "Pick two classic scoops to share — or keep both.",
    "Bugis",
    "200 Victoria Street",
    1.299,
    103.855,
  ],
  [
    "Green Sip",
    "A fresh reason to take a break.",
    "Drinks",
    "30% off",
    "Freshly brewed tea for your mid-afternoon reset.",
    "Orchard",
    "2 Orchard Turn",
    1.304,
    103.832,
  ],
  [
    "The Noodle Room",
    "Good noodles. Better lunch.",
    "Meals",
    "Set $12",
    "A bowl, a side and a drink for your next catch-up.",
    "Chinatown",
    "133 New Bridge Road",
    1.285,
    103.844,
  ],
  [
    "Butter Days",
    "Something sweet on the way home.",
    "Cafés",
    "1-for-1",
    "A buttery pastry pairing for a slow afternoon.",
    "Tiong Bahru",
    "302 Tiong Bahru Road",
    1.286,
    103.827,
  ],
] as const;
export function demoPromotions(): Promotion[] {
  const now = DateTime.now().setZone(zone);
  return details.map((d, i) => ({
    id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
    merchant: d[0],
    title: d[1],
    category: d[2],
    benefit: d[3],
    description: d[4],
    terms: [
      "Synthetic example only — this offer cannot be redeemed.",
      "Dine-in example. One redemption per customer. While stocks last.",
    ],
    startDate: now.minus({ days: 3 }).toISODate()!,
    endDate: now.plus({ days: i + 2 }).toISODate()!,
    weekdays: i === 1 ? [1, 2, 3, 4, 5] : null,
    hours: { start: "10:00", end: "21:00" },
    scheduleLabel: i === 1 ? "Weekdays · 10am–9pm" : "Daily · 10am–9pm",
    excludePublicHolidays: false,
    holidayDates: [],
    holidayCalendarThrough: null,
    outlets: [
      {
        id: `10000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
        name: d[5],
        address: d[6],
        lat: d[7],
        lng: d[8],
        evidence:
          "Synthetic demo outlet, not a verified participating merchant.",
        verifiedAt: now.toUTC().toISO()!,
      },
    ],
    sources: [
      {
        label: i % 2 ? "TasteSoul" : "SG Food Deals",
        url: `https://t.me/${i % 2 ? "tastesoulsg" : "sgfooddeals"}/1`,
      },
    ],
    verifiedAt: now.toUTC().toISO()!,
    reviewDueAt: null,
    status: "published",
    revision: 1,
  }));
}
