server {
  listen 80;
  location /auth/v1/ {
    if ($request_method = OPTIONS) {
      add_header Access-Control-Allow-Origin "http://127.0.0.1:3100" always;
      add_header Access-Control-Allow-Headers "authorization, apikey, content-type, x-client-info, x-supabase-api-version" always;
      add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
      return 204;
    }
    proxy_pass http://auth:9999/;
    proxy_hide_header Access-Control-Allow-Origin;
    add_header Access-Control-Allow-Origin "http://127.0.0.1:3100" always;
  }
}
