import { readFile, writeFile } from "node:fs/promises";
import assert from "node:assert/strict";
import { DateTime } from "luxon";
import { mvpPromotionSchema, visibleMvp } from "../src/domain/mvp";
import { digest } from "../src/ingestion/resolution/cache";
const directory = "docs/changes/mvp-source-location";
const baseline = JSON.parse(
  await readFile(`${directory}/baseline.json`, "utf8"),
);
const artifact = JSON.parse(await readFile("data/mvp-promotions.json", "utf8"));
const records = (artifact.records as unknown[]).map((p: unknown) =>
  mvpPromotionSchema.parse(p),
);
const original = (baseline.records as unknown[]).map((p: unknown) =>
  mvpPromotionSchema.parse(p),
);
assert.equal(original.length, 28);
assert.equal(new Set(original.map((p) => p.id)).size, 28);
const rows = original.map((old) => {
  const matches = records.filter((p) => p.id === old.id);
  assert.equal(matches.length, 1, old.id);
  const p = matches[0];
  assert.equal(p.contentStatus, "resolved");
  assert.equal(p.validityStatus, "resolved");
  assert.ok(p.locationAudit.length, p.id);
  for (const a of p.locationAudit) {
    assert.ok(
      [
        "google_merchant_place_resolved",
        "merchant_place_match_failed",
        "merchant_place_ambiguous",
        "merchant_place_closed_or_unavailable",
      ].includes(a.merchantResult),
      `${p.id}: ${a.merchantResult}`,
    );
    if (
      a.sourceLocation &&
      a.merchantResult !== "google_merchant_place_resolved"
    )
      assert.ok(
        a.fallbackQuery || a.fallbackResult === "source_location_too_vague",
        p.id,
      );
    assert.ok(
      !/cache|fetch|Provider/.test(a.fallbackResult),
      `${p.id}: ${a.fallbackResult}`,
    );
  }
  return {
    id: p.id,
    sourceUrl: p.sourceUrl,
    merchant: p.merchant,
    sourceLocation: p.locationAudit.map((a) => a.sourceLocation),
    oldReason: old.reasons,
    originallyCacheMissing: old.reasons.some((r) => r.includes("not_cached")),
    lookups: p.locationAudit,
    finalCoordinateBasis: [...new Set(p.outlets.map((o) => o.coordinateBasis))],
    finalStatus: p.status,
    finalMapStatus: p.mapStatus,
    remainingReasons: p.reasons,
    outlets: p.outlets,
  };
});
const summary = {
  beforePrimaryNeedsLocation: 28,
  afterPrimaryNeedsLocation: rows.filter(
    (r) => r.finalStatus === "needs_location",
  ).length,
  resolvedByMerchantOnly: rows.filter(
    (r) =>
      r.finalStatus === "ready" &&
      r.finalCoordinateBasis.length === 1 &&
      r.finalCoordinateBasis[0] === "google_merchant_place",
  ).length,
  resolvedWithSourceFallback: rows.filter(
    (r) =>
      r.finalStatus === "ready" &&
      r.finalCoordinateBasis.includes("google_source_location"),
  ).length,
  originallyCacheMissing: rows.filter((r) => r.originallyCacheMissing).length,
  resolvedMerelyByCacheRefresh: rows.filter(
    (r) =>
      r.originallyCacheMissing &&
      r.finalStatus === "ready" &&
      !r.finalCoordinateBasis.includes("google_source_location"),
  ).length,
  totalMapReady: records.filter((p) => p.mapStatus === "ready").length,
  artifactEvaluatedAt: artifact.evaluatedAt,
  activeLiveReadyAtArtifactDate: visibleMvp(
    records,
    false,
    DateTime.fromISO(artifact.evaluatedAt),
  ).length,
  activeLiveReadyAtTaskDate: visibleMvp(
    records,
    false,
    DateTime.fromISO("2026-09-22T12:00:00+08:00"),
  ).length,
};
await writeFile(
  `${directory}/ledger.json`,
  JSON.stringify({ summary, records: rows }, null, 2) + "\n",
);
const escape = (s: string) => s.replaceAll("|", "\\|").replaceAll("\n", " ");
await writeFile(
  `${directory}/ledger.md`,
  `# Original 28 location records\n\nGenerated by scripts/audit-mvp-locations.ts from the frozen baseline and current artifact. Cache-refresh-only is a subset of merchant-only resolutions, not an additional category. Ready may have partial location coverage; each unresolved named location remains in the audit.\n\n\`\`\`json\n${JSON.stringify(summary, null, 2)}\n\`\`\`\n\n| Record ID | Source | Merchant | Source location | Old reason | Merchant lookup | Fallback lookup | Final coordinate basis | Final status |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n` +
    rows
      .map(
        (r) =>
          `| ${r.id} | [post](${r.sourceUrl}) | ${escape(r.merchant)} | ${escape(r.sourceLocation.map((s) => s ?? "No source-named physical location").join("; "))} | ${escape(r.oldReason.join("; "))} | ${escape(r.lookups.map((a) => `${a.sourceLocation ?? "merchant search"}: ${a.merchantResult}`).join("; "))} | ${escape(r.lookups.map((a) => `${a.sourceLocation ?? "merchant search"}: ${a.fallbackResult}`).join("; "))} | ${r.finalCoordinateBasis.join("; ") || "none"} | ${r.finalStatus} |`,
      )
      .join("\n") +
    "\n",
);
if (process.argv.includes("--capture")) {
  const captured = new Map<string, unknown>();
  const searched = new Set<string>();
  for (const row of rows)
    for (const audit of row.lookups) {
      for (const [query, sourceLocation] of [
        [audit.merchantQuery, false],
        [audit.fallbackQuery, true],
      ] as const) {
        if (!query) continue;
        const searchKey = `${sourceLocation}:${query
          .normalize("NFKC")
          .toLowerCase()
          .replace(/[’']/g, "")
          .replace(/[^\p{L}\p{N}]+/gu, " ")
          .trim()}`;
        if (searched.has(searchKey)) continue;
        searched.add(searchKey);
        let pageToken: string | undefined;
        do {
          const fields =
            "places.id,places.displayName,places.formattedAddress,places.businessStatus,places.location,places.addressComponents,nextPageToken" +
            (sourceLocation ? ",places.types" : "");
          const body = JSON.stringify({
            textQuery: query,
            regionCode: "SG",
            languageCode: "en",
            pageSize: 20,
            locationRestriction: {
              rectangle: {
                low: { latitude: 1.15, longitude: 103.6 },
                high: { latitude: 1.5, longitude: 104.1 },
              },
            },
            ...(pageToken ? { pageToken } : {}),
          });
          const key = digest(sourceLocation ? { body, fields } : body);
          const cache = JSON.parse(
            await readFile(`.local/mvp-google/${key}.json`, "utf8"),
          );
          const response = JSON.parse(cache.text);
          captured.set(key, {
            query,
            pageToken: pageToken ?? null,
            sourceLocation,
            fetchedAt: new Date(cache.fetchedAt).toISOString(),
            response,
          });
          pageToken = response.nextPageToken;
        } while (pageToken);
      }
    }
  await writeFile(
    "tests/fixtures/mvp-location-google.json",
    JSON.stringify([...captured.values()], null, 2) + "\n",
  );
}
console.log(JSON.stringify(summary, null, 2));
