CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS app;
REVOKE ALL ON SCHEMA app FROM PUBLIC;
DO $$ BEGIN
 IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname='promotion_web') THEN CREATE ROLE promotion_web NOLOGIN; END IF;
 IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname='promotion_admin') THEN CREATE ROLE promotion_admin NOLOGIN; END IF;
 IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname='promotion_ingest') THEN CREATE ROLE promotion_ingest NOLOGIN; END IF;
END $$;
CREATE TABLE app.administrators(user_id uuid PRIMARY KEY);
CREATE TABLE app.sources(id text PRIMARY KEY,label text NOT NULL,last_attempt timestamptz,last_success timestamptz,checkpoint bigint NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'Never checked');
INSERT INTO app.sources(id,label) VALUES('sgfooddeals','SG Food Deals'),('tastesoulsg','TasteSoul');
CREATE TABLE app.source_posts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),source_id text NOT NULL REFERENCES app.sources(id),message_id bigint NOT NULL,permalink text NOT NULL,published_at timestamptz NOT NULL,hash text NOT NULL,UNIQUE(source_id,message_id));
CREATE TABLE app.post_revisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),post_id uuid NOT NULL REFERENCES app.source_posts(id),hash text NOT NULL,evidence jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(post_id,hash));
CREATE TABLE app.processing_attempts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),revision_id uuid NOT NULL REFERENCES app.post_revisions(id),parser_version text NOT NULL,outcome text NOT NULL,issues jsonb NOT NULL DEFAULT '[]',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.candidates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),revision_id uuid NOT NULL REFERENCES app.post_revisions(id),candidate_key text NOT NULL,data jsonb,issues jsonb NOT NULL DEFAULT '[]',status text NOT NULL DEFAULT 'needs_review',UNIQUE(revision_id,candidate_key));
CREATE TABLE app.promotions(id uuid PRIMARY KEY,merchant text NOT NULL,fingerprint text NOT NULL,status text NOT NULL CHECK(status IN('published','needs_review','withdrawn')),revision integer NOT NULL DEFAULT 1,admin_corrected boolean NOT NULL DEFAULT false,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX promotion_fingerprint ON app.promotions(fingerprint);
CREATE TABLE app.outlets(id uuid PRIMARY KEY,data jsonb NOT NULL,location geography(Point,4326) NOT NULL);
CREATE INDEX outlets_geography ON app.outlets USING gist(location);
CREATE INDEX outlets_geometry ON app.outlets USING gist((location::geometry));
CREATE TABLE app.promotion_outlets(promotion_id uuid REFERENCES app.promotions(id),outlet_id uuid REFERENCES app.outlets(id),PRIMARY KEY(promotion_id,outlet_id));
CREATE TABLE app.promotion_sources(promotion_id uuid REFERENCES app.promotions(id),post_id uuid REFERENCES app.source_posts(id),PRIMARY KEY(promotion_id,post_id));
CREATE TABLE app.review_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),promotion_id uuid REFERENCES app.promotions(id),actor uuid NOT NULL,action text NOT NULL,reason text NOT NULL,before_data jsonb,after_data jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.sync_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),source_id text REFERENCES app.sources(id),started_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz,outcome text NOT NULL DEFAULT 'running',counts jsonb NOT NULL DEFAULT '{}',error text);
GRANT USAGE ON SCHEMA app TO promotion_web,promotion_admin,promotion_ingest;
GRANT SELECT ON app.promotions,app.outlets,app.promotion_outlets,app.sources TO promotion_web;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA app TO promotion_admin,promotion_ingest;
REVOKE ALL ON app.administrators FROM promotion_ingest;
ALTER TABLE app.promotions ENABLE ROW LEVEL SECURITY;
CREATE POLICY published_read ON app.promotions FOR SELECT TO promotion_web USING(status='published');
CREATE POLICY admin_all ON app.promotions TO promotion_admin USING(true) WITH CHECK(true);
CREATE POLICY ingest_all ON app.promotions TO promotion_ingest USING(true) WITH CHECK(true);
